version: '3'

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - .data:/data/postgres
      - ./apps/api/migrations:/docker-entrypoint-initdb.d

volumes:
  db:
