name: Trigger auto deployment for samovar-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/deployment.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  job1:
    name: Build and push backend API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMOVARAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: samovardcr.azurecr.io
          registryUsername: ${{ secrets.SAMOVARAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMOVARAPI_REGISTRY_PASSWORD }}
          containerAppName: samovar-api
          resourceGroup: Samovar
          dockerfilePath: apps/api/Dockerfile
          imageToBuild: samovardcr.azurecr.io/samovar-api:${{ github.sha }}

  job2:
    name: Build and deploy telegram bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TELEGRAMBOT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: samovardcr.azurecr.io
          registryUsername: ${{ secrets.TELEGRAMBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TELEGRAMBOT_REGISTRY_PASSWORD }}
          containerAppName: telegram-bot
          resourceGroup: Samovar
          dockerfilePath: apps/telegram-bot/Dockerfile
          imageToBuild: samovardcr.azurecr.io/telegram-bot:${{ github.sha }}
