name: Continuous integration

on: pull_request

jobs:
  build-mini-app:
    name: Build mini-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run docker compose
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.ci.yml"
