name: Trigger auto deployment for telegram-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'apps/telegram-bot/**'
    - '.github/workflows/telegram-bot-AutoDeployTrigger-39e29065-6a82-4560-8c6b-3698a6cc8d16.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TELEGRAMBOT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}apps/telegram-bot 
          registryUrl: samovardcr.azurecr.io
          registryUsername: ${{ secrets.TELEGRAMBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TELEGRAMBOT_REGISTRY_PASSWORD }}
          containerAppName: telegram-bot
          resourceGroup: Samovar
          imageToBuild: samovardcr.azurecr.io/telegram-bot:${{ github.sha }}
          dockerfilePath: Dockerfile

     

